finance_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),  
    path('profile/', views.profile, name='profile'),
    path('add_income/', views.add_income, name='add_income'),
    path('add_expense/', views.add_expense, name='add_expense'),
    path('edit_income/<int:id>/', views.edit_income, name='edit_income'),
    path('edit_expense/<int:id>/', views.edit_expense, name='edit_expense'),
    path('delete_income/<int:id>/', views.delete_income, name='delete_income'),
    path('delete_expense/<int:id>/', views.delete_expense, name='delete_expense'),
    path('report/', views.report, name='report'),
    path('add_budget/', views.add_budget, name='add_budget'),
    path('budget_progress/', views.budget_progress, name='budget_progress'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('all-incomes/', views.all_incomes, name='all_incomes'),
    path('all-expenses/', views.all_expenses, name='all_expenses'),
    path('api/chart-data/', views.chart_data, name='chart_data'),
]

tracker/models.py
from django.db import models
from django.contrib.auth.models import User

class Income(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    source = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    description = models.TextField()
    title = models.CharField(max_length=100,default="Untitled Income") 

    def __str__(self):
        return f"{self.source} - {self.amount}"

class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    description = models.TextField()
    title = models.CharField(max_length=100,default="Untitled Income") 
    
    def __str__(self):
        return f"{self.category} - {self.amount}"



class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=100)
    limit = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.category} - {self.limit}"

tracker/forms.py
# tracker/forms.py
from django import forms
from .models import Income, Expense, Budget
from datetime import date

class DateInput(forms.DateInput):
    input_type = 'date'

class IncomeForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    class Meta:
        model = Income
        fields = ['title','source', 'amount', 'date', 'description']
        widgets = {
            'date': DateInput(attrs={'max': date.today().isoformat()}),
        }

class ExpenseForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    class Meta:
        model = Expense
        fields = ['title','category', 'amount', 'date', 'description']
        widgets = {
            'date': DateInput(attrs={'max': date.today().isoformat()}),
        }


class BudgetForm(forms.ModelForm):
    class Meta:
        model = Budget
        fields = ['category', 'limit']

tracker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Income, Expense, Budget
from .forms import IncomeForm, ExpenseForm,BudgetForm
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from datetime import datetime
from decimal import Decimal 
from django.http import JsonResponse


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')  # Redirect to the desired page after login
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def profile(request):
    # return render(request, 'registration/profile.html')
    return render(request, 'tracker/index.html')

def add_income(request):
    if request.method == 'POST':
        form = IncomeForm(request.POST)
        if form.is_valid():
            income = form.save(commit=False)
            income.user = request.user
            income.save()
            return redirect('all_incomes')
    else:
        form = IncomeForm()
    return render(request, 'tracker/add_income.html', {'form': form})

def add_expense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.user = request.user
            expense.save()
            return redirect('all_expenses')
    else:
        form = ExpenseForm()
    return render(request, 'tracker/add_expense.html', {'form': form})

def edit_income(request, id):
    income = get_object_or_404(Income, id=id, user=request.user)
    if request.method == 'POST':
        form = IncomeForm(request.POST, instance=income)
        if form.is_valid():
            form.save()
            return redirect('all_incomes')
    else:
        form = IncomeForm(instance=income)
    return render(request, 'tracker/edit_income.html', {'form': form})

def edit_expense(request, id):
    expense = get_object_or_404(Expense, id=id, user=request.user)
    if request.method == 'POST':
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            return redirect('all_expenses')
    else:
        form = ExpenseForm(instance=expense)
    return render(request, 'tracker/edit_expense.html', {'form': form})

def delete_income(request, id):
    income = get_object_or_404(Income, id=id, user=request.user)
    income.delete()
    return redirect('all_incomes')

def delete_expense(request, id):
    expense = get_object_or_404(Expense, id=id, user=request.user)
    expense.delete()

    total_income = Income.objects.filter(user=request.user).aggregate(Sum('amount'))['amount__sum'] or 0
    total_expenses = Expense.objects.filter(user=request.user).aggregate(Sum('amount'))['amount__sum'] or 0
    savings = total_income - total_expenses



    context = {
        'total_income': total_income,
        'total_expenses': total_expenses,
        'savings': savings,
    }
    return render(request, 'tracker/index.html', context)


@login_required
def report(request):
    income_by_month = Income.objects.filter(user=request.user).extra(select={'month': 'strftime("%%Y-%%m", date)'}).values('month').annotate(total_amount=Sum('amount')).order_by('month')
    expense_by_month = Expense.objects.filter(user=request.user).extra(select={'month': 'strftime("%%Y-%%m", date)'}).values('month').annotate(total_amount=Sum('amount')).order_by('month')

    context = {
        'income_by_month': income_by_month,
        'expense_by_month': expense_by_month,
    }
    return render(request, 'tracker/report.html', context)


@login_required
def add_budget(request):
    if request.method == 'POST':
        form = BudgetForm(request.POST)
        if form.is_valid():
            budget = form.save(commit=False)
            budget.user = request.user
            budget.save()
            return redirect('budget_progress')
    else:
        form = BudgetForm()
    return render(request, 'tracker/add_budget.html', {'form': form})

@login_required
def budget_progress(request):
    budgets = Budget.objects.filter(user=request.user)
    expenses = Expense.objects.filter(user=request.user)
    budget_status = []

    for budget in budgets:
        spent = expenses.filter(category=budget.category).aggregate(Sum('amount'))['amount__sum'] or 0
        status = {
            'category': budget.category,
            'limit': budget.limit,
            'spent': spent,
            'remaining': budget.limit - spent,
        }
        budget_status.append(status)

    context = {'budget_status': budget_status}
    return render(request, 'tracker/budget_progress.html', context)



@login_required
def dashboard(request):
    # Get all incomes and expenses for the logged-in user
    incomes = Income.objects.filter(user=request.user)
    expenses = Expense.objects.filter(user=request.user)

    # Calculate total income, total expenses, and total savings
    total_income = incomes.aggregate(Sum('amount'))['amount__sum'] or 0
    total_expenses = expenses.aggregate(Sum('amount'))['amount__sum'] or 0
    total_savings = total_income - total_expenses

    # Calculate monthly income and expenses
    income_data = []
    expenses_data = []
    months = []

    for month in range(1, 13):
        month_name = datetime(1900, month, 1).strftime('%B')
        months.append(month_name)
        
        monthly_income = incomes.filter(date__month=month).aggregate(Sum('amount'))['amount__sum'] or 0
        income_data.append(int(monthly_income))
        
        monthly_expenses = expenses.filter(date__month=month).aggregate(Sum('amount'))['amount__sum'] or 0
        expenses_data.append(int(monthly_expenses))

    # Prepare context for rendering the template
    context = {
        'total_income': total_income,
        'total_expenses': total_expenses,
        'total_savings': total_savings,
        'months': months,
        'income_data': income_data,
        'expenses_data': expenses_data,
    }
    
    return render(request, 'tracker/dashboard.html', context)


def chart_data(request):
    # Get all incomes and expenses for the logged-in user
    incomes = Income.objects.filter(user=request.user)
    expenses = Expense.objects.filter(user=request.user)

    # Calculate total income, total expenses, and total savings
    total_income = incomes.aggregate(Sum('amount'))['amount__sum'] or 0
    total_expenses = expenses.aggregate(Sum('amount'))['amount__sum'] or 0
    total_savings = total_income - total_expenses

    # Calculate monthly income and expenses
    income_data = []
    expenses_data = []
    months = []

    for month in range(1, 13):
        month_name = datetime(1900, month, 1).strftime('%B')
        months.append(month_name)
        
        monthly_income = incomes.filter(date__month=month).aggregate(Sum('amount'))['amount__sum'] or 0
        income_data.append(int(monthly_income))
        
        monthly_expenses = expenses.filter(date__month=month).aggregate(Sum('amount'))['amount__sum'] or 0
        expenses_data.append(int(monthly_expenses))

    data = {
        'months': months,
        'income_data': income_data,
        'expenses_data': expenses_data,
    }
    return JsonResponse(data)


@login_required
def all_incomes(request):
    all_incomes = Income.objects.filter(user=request.user)  # Assuming you have a way to filter incomes for the current user
    return render(request, 'tracker/all_incomes.html', {'all_incomes': all_incomes})


@login_required
def all_expenses(request):
    all_expenses = Expense.objects.filter(user=request.user)  # Assuming you have a way to filter expenses for the current user
    return render(request, 'tracker/all_expenses.html', {'all_expenses': all_expenses})


@login_required
def index(request):
    # Calculate total income, total expenses, and total savings
    all_income = Income.objects.filter(user=request.user).aggregate(Sum('amount'))['amount__sum'] or 0
    all_expenses = Expense.objects.filter(user=request.user).aggregate(Sum('amount'))['amount__sum'] or 0
    all_savings = all_income - all_expenses

     # Get the current year and month
    current_year = datetime.now().year
    current_month = datetime.now().month

    # Get selected year and month from GET parameters, default to current year and month
    selected_year = int(request.GET.get('year', current_year))
    selected_month = int(request.GET.get('month', current_month))

    # Get the past 5 years
    years = [current_year - i for i in range(5)]
    # Define months
    months = [(i, datetime(2000, i, 1).strftime('%B')) for i in range(1, 13)]

    # Filter income and expenses based on selected year and month
    filtered_income = Income.objects.filter(date__year=selected_year, date__month=selected_month)
    filtered_expenses = Expense.objects.filter(date__year=selected_year, date__month=selected_month)

tracker/templates/tracker/add_budget.html
{% extends 'tracker/base.html' %}

{% block title %}Add Budget{% endblock %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', Arial, sans-serif;
        /* Use Roboto font */
        background-color: #121212;
        /* Dark background */
        color: #e0e0e0;
        /* Light text color */
        padding: 20px;
        /* Added padding for better spacing */
    }

    h2 {
        text-align: center;
        color: #ffffff;
        /* White color for the heading */
        margin-bottom: 20px;
        font-weight: 500;
    }

    .add-budget {
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #1e1e1e;
        /* Dark background */
    }

    form label {
        display: block;
        text-align: start;
        margin-bottom: 5px;
        font-weight: bold;
        color: #e0e0e0;
        /* Light text color for labels */
    }

    form input[type="text"],
    form input[type="number"],
    form select {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Light background color for form fields */
        color: #333;
        /* Dark text color for form fields */
    }

    form .add-budget-btn {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    form .add-budget-btn:hover {
        background-color: #0056b3;
    }
</style>
<h2>Add Budget</h2>
<form method="post" class="add-budget">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <label for="id_category">Category:</label>
    {{ form.category }}
    <label for="id_limit">Limit:</label>
    {{ form.limit }}
    <button type="submit" class="add-budget-btn">Add Budget</button>
</form>
</body>

{% endblock %}

tracker/templates/tracker/add_expense.html
{% extends 'tracker/base.html' %}

{% block title %}Add Expense{% endblock %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', Arial, sans-serif;
        /* Use Roboto font */
        background-color: #121212;
        /* Dark background */
        color: #e0e0e0;
        /* Light text color */
        padding: 20px;
        /* Added padding for better spacing */
    }

    h2 {
        text-align: center;
        color: #ffffff;
        /* White color for the heading */
        margin-bottom: 20px;
        font-weight: 500;
    }

    .add-expense {
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #1e1e1e;
        /* Dark background */
    }

    form label {
        display: block;
        text-align: start;
        margin-bottom: 5px;
        font-weight: bold;
        color: #e0e0e0;
        /* Light text color for labels */
    }

    form input[type="text"],
    form input[type="number"],
    form input[type="date"],
    form select {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Light background color for form fields */
        color: #333;
        /* Dark text color for form fields */
    }

    form textarea {
        width: 100%;
        height: 40px;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Light background color for form fields */
        color: #333;
    }

    form .add-expense-btn {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    form .add-expense-btn:hover {
        background-color: #0056b3;
    }
</style>
<h2>Add Expense</h2>
<form method="post" class="add-expense">
    {% csrf_token %}
    <label for="id_title">Title:</label>
    {{ form.title }}
    <label for="id_description">Description:</label>
    {{ form.description }}
    <label for="id_amount">Amount:</label>
    {{ form.amount }}
    <label for="id_date">Date:</label>
    {{ form.date }}
    <label for="id_category">Category:</label>
    {{ form.category }}
    <button type="submit" class="add-expense-btn">Add Expense</button>
</form>
</body>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dateInput = document.querySelector('input[type="date"]');
        const today = new Date().toISOString().split('T')[0];
        dateInput.setAttribute('max', today);
    });
</script>

{% endblock %}

tracker/templates/tracker/add_income.html
{% extends 'tracker/base.html' %}

{% block title %}Add Income{% endblock %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', Arial, sans-serif;
        background-color: #121212;
        /* Dark background */
        color: #e0e0e0;
        /* Light text color */
        padding: 20px;
    }

    h2 {
        text-align: center;
        color: #ffffff;
        /* White color for the heading */
        margin-bottom: 20px;
        font-weight: 500;
    }

    .add-income {
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #333;
        /* Dark border */
        border-radius: 5px;
        background-color: #1e1e1e;
        /* Dark background */

    }

    form label {
        display: block;
        text-align: start;
        margin-bottom: 5px;
        font-weight: bold;
        color: #ffffff;
        /* White color for labels */
    }

    form input[type="text"],
    form input[type="number"],
    form input[type="date"],
    form textarea,
    form select {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #333;
        /* Dark border */
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Dark background */
        color: #333;

        /* White color for text */
    }

    form textarea {
        width: 100%;
        height: 40px;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Light background color for form fields */
        color: #333;
    }

    form .add-income-btn {
        background-color: #007bff;
        /* Blue color for button */
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    form button[type="submit"]:hover {
        background-color: #0056b3;
        /* Darker blue on hover */
    }
</style>

<h2>Add Income</h2>
<form method="post" class="add-income">
    {% csrf_token %}
    <label for="id_title">Title:</label>
    {{ form.title }}
    <label for="id_description">Description:</label>
    {{ form.description }}
    <label for="id_amount">Amount:</label>
    {{ form.amount }}
    <label for="id_date">Date:</label>
    {{ form.date }}
    <label for="id_source">Category:</label>
    {{ form.source }}
    <button type="submit" class="add-income-btn">Add Income</button>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dateInput = document.querySelector('input[type="date"]');
        const today = new Date().toISOString().split('T')[0];
        dateInput.setAttribute('max', today);
    });
</script>

{% endblock %}

tracker/templates/tracker/all_expenses.html
{% extends 'tracker/base.html' %}

{% block title %}All Expenses{% endblock %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', Arial, sans-serif;
        /* Use Roboto font */
        background-color: #121212;
        /* Dark background */
        color: #e0e0e0;
        /* Light text color */
        padding: 20px;
        /* Added padding for better spacing */
    }

    h2 {
        text-align: center;
        color: #ffffff;
        /* White color for the heading */
        margin-bottom: 20px;
        font-weight: 500;
    }

    ul {
        list-style-type: none;
        padding: 0;
        /* Removed default padding */
        display: flex;
        flex-direction: row;
        justify-content: center;
        flex-wrap: wrap;
        gap: 20px;
    }

    li {
        width: 350px;
        height: 200px;
        /* Increased height for better spacing */
        border: 2px solid #6a1b9a;
        /* Dark border */
        border-radius: 10px;
        padding: 20px;
        /* Increased padding for better spacing */
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        background-color: #1e1e1e;
        /* Dark background */
    }

    .item {
        color: #e0e0e0;
        /* Light text color for item details */
        margin-bottom: 10px;
        /* Added margin for better spacing between items */
    }

    .buttons {
        display: flex;
        width: 100%;
        justify-content: space-between;
        gap: 10px;
    }

    .edit-expense-btn,
    .delete-expense-btn {
        background-color: #1e88e5;
        /* Blue color for buttons */
        border-radius: 10px;
        padding: 10px 0px;
        color: white;
        width: 45%;
        border: none;
        text-align: center;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .delete-expense-btn {
        background-color: #e53935;
        /* Red color for delete button */
    }

    .edit-expense-btn:hover {
        background-color: #1565c0;
        /* Darker blue/red on hover */
    }

    .delete-expense-btn:hover {
        background-color: rgb(235, 147, 147);
        /* Darker blue/red on hover */
    }
</style>
<h2>All Expenses</h2>
<ul id="expense-list">
    {% for expense in all_expenses %}
    <li>
        <div class="item">
            <strong>Title:</strong> {{ expense.title}}
        </div>

        <div class="item">
            <strong>Description:</strong> {{ expense.description }}
        </div>

        <div class="item">
            <strong>Amount:</strong> ${{ expense.amount }}<br>
        </div>

        <div class="item">
            <strong>Date:</strong> {{ expense.date }}<br>
        </div>

        <div class="item">
            <strong>Category:</strong> {{ expense.category }}<br>
        </div>

        <div class="buttons">

            <button class="edit-expense-btn" data-id="{{ expense.id }}">Update</button>
            <button class="delete-expense-btn" data-id="{{ expense.id }}">Delete</button>
        </div>
    </li>
    {% endfor %}
</ul>

{% endblock %}

tracker/templates/tracker/edit_expense.html
{% extends 'tracker/base.html' %}

{% block title %}Edit Expense{% endblock %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', Arial, sans-serif;
        background-color: #121212;
        /* Dark background */
        color: #e0e0e0;
        /* Light text color */
        padding: 20px;
    }

    h2 {
        text-align: center;
        color: #ffffff;
        /* White color for the heading */
        margin-bottom: 20px;
        font-weight: 500;
    }

    .edit-expense {
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #333;
        /* Dark border */
        border-radius: 5px;
        background-color: #1e1e1e;
        /* Dark background */
    }

    form label {
        display: block;
        text-align: start;
        margin-bottom: 5px;
        font-weight: bold;
        color: #ffffff;
        /* White color for labels */
    }

    form input[type="text"],
    form input[type="number"],
    form input[type="date"],
    form textarea,
    form select {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #333;
        /* Dark border */
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Dark background */
        color: #333;
        /* White color for text */
    }

    form textarea {
        width: 100%;
        height: 40px;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Light background color for form fields */
        color: #333;
    }

    form .edit-expense-btn {
        background-color: #007bff;
        /* Blue color for button */
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    form button[type="submit"]:hover {
        background-color: #0056b3;
        /* Darker blue on hover */
    }
</style>
<h2>Edit Expense</h2>
<form method="post" class="edit-expense">
    {% csrf_token %}
    <label for="id_title">Title:</label>
    {{ form.title }}
    <label for="id_description">Description:</label>
    {{ form.description }}
    <label for="id_amount">Amount:</label>
    {{ form.amount }}
    <label for="id_date">Date:</label>
    {{ form.date }}
    <label for="id_category">Category:</label>
    {{ form.category }}
    <button type="submit" class="edit-expense-btn">Update Expense</button>
</form>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dateInput = document.querySelector('input[type="date"]');
        const today = new Date().toISOString().split('T')[0];
        dateInput.setAttribute('max', today);
    });
</script>

{% endblock %}

tracker/templates/tracker/edit_income.html
{% extends 'tracker/base.html' %}

{% block title %}Edit Income{% endblock %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', Arial, sans-serif;
        background-color: #121212;
        /* Dark background */
        color: #e0e0e0;
        /* Light text color */
        padding: 20px;
    }

    h2 {
        text-align: center;
        color: #ffffff;
        /* White color for the heading */
        margin-bottom: 20px;
        font-weight: 500;
    }

    .edit-income {
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #333;
        /* Dark border */
        border-radius: 5px;
        background-color: #1e1e1e;
        /* Dark background */
    }

    form label {
        display: block;
        text-align: start;
        margin-bottom: 5px;
        font-weight: bold;
        color: #ffffff;
        /* White color for labels */
    }

    form input[type="text"],
    form input[type="number"],
    form input[type="date"],
    form textarea,
    form select {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #333;
        /* Dark border */
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Dark background */
        color: #333;
        /* White color for text */
    }

    form textarea {
        width: 100%;
        height: 40px;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        background-color: #fff;
        /* Light background color for form fields */
        color: #333;
    }

    form .edit-income-btn {
        background-color: #007bff;
        /* Blue color for button */
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    form button[type="submit"]:hover {
        background-color: #0056b3;
        /* Darker blue on hover */
    }
</style>
<h2>Edit Income</h2>
<form method="post" class="edit-income">
    {% csrf_token %}
    <label for="id_title">Title:</label>
    {{ form.title }}
    <label for="id_description">Description:</label>
    {{ form.description }}
    <label for="id_amount">Amount:</label>
    {{ form.amount }}
    <label for="id_date">Date:</label>
    {{ form.date }}
    <label for="id_source">Category:</label>
    {{ form.source }}
    <button type="submit" class="edit-income-btn">Update Income</button>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dateInput = document.querySelector('input[type="date"]');
        const today = new Date().toISOString().split('T')[0];
        dateInput.setAttribute('max', today);
    });
</script>
{% endblock %}

tracker/templates/tracker/report.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Report</title>
</head>

<body>
    <h2>Monthly Income vs Expenses Report</h2>
    <h3>Income</h3>
    <ul>
        {% for item in income_by_month %}
        <li>{{ item.month }}: {{ item.total_amount }}</li>
        {% endfor %}
    </ul>
    <h3>Expenses</h3>
    <ul>
        {% for item in expense_by_month %}
        <li>{{ item.month }}: {{ item.total_amount }}</li>
        {% endfor %}
    </ul>
</body>

</html>